# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import passport_pb2 as passport__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in passport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PassportServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPassportInfos = channel.unary_unary(
                '/passport.PassportService/GetPassportInfos',
                request_serializer=passport__pb2.PassportInfosRequest.SerializeToString,
                response_deserializer=passport__pb2.PassportInfos.FromString,
                _registered_method=True)


class PassportServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPassportInfos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PassportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPassportInfos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPassportInfos,
                    request_deserializer=passport__pb2.PassportInfosRequest.FromString,
                    response_serializer=passport__pb2.PassportInfos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'passport.PassportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('passport.PassportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PassportService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPassportInfos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passport.PassportService/GetPassportInfos',
            passport__pb2.PassportInfosRequest.SerializeToString,
            passport__pb2.PassportInfos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
